name: Terraform Dev

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true

jobs:

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Login to Azure using GitHub OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: ./envs/dev
        run: terraform init -reconfigure

      # 5. Terraform Format Check
      - name: Terraform Format Check
        working-directory: ./envs/dev
        run: terraform fmt -check

      # 6. Terraform Validate
      - name: Terraform Validate
        working-directory: ./envs/dev
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        working-directory: ./envs/dev
        run: terraform plan -out=tfplan

      # 8. Upload the generated plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./envs/dev/tfplan


  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan

    # Apply only after merge/push to main
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    # GitHub Environment approval
    # environment:
    #   name: dev

    permissions:
      contents: read
      id-token: write

    steps:

      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Azure OIDC Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: ./envs/dev
        run: terraform init -reconfigure

      # 5. Download the exact plan generated above
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ./envs/dev

      # 6. Apply the exact plan
      - name: Terraform Apply
        working-directory: ./envs/dev
        run: terraform apply -auto-approve tfplan
